### ISSUE TITLE
drawer_hestiaUI content are blocking trigger button when closed.

### ISSUE THREAD

**Issue by hollowaykeanho** [ZORALab/Hestia#70] opened 2023-02-14 03:04 UTC
# Description
```
Please provide a short description of what you have encountered below.
```
When closed, the `drawer_hestiaUI` content is blocking its trigger button which cause an accidental misclick. See screenshot below:

![screenshot-2023-02-14-11-00-21](https://user-images.githubusercontent.com/7259572/218628159-d2dc61dd-9427-4456-bc46-c7a0f2e836bf.jpg)

# Expected Behavior
```
Please specify the expected behavior of your usage below.
```
drawer content is invisible and unclickable when closed.

# Current Behavior
```
Please specify the current behavior of software below.
```
drawer content is blocking the trigger button from being pressed.

# Steps to Reproduce (COMPULSORY)
```
Please specify all the steps required to re-produce the problem.
```
1. Deploy a site and go into debug console.
2. Squeeze your screen to small dimension (e.g. `Galaxy Fold` device in `Chrome` browser).
3. Observe the drawer. Clicking on trigger button can accidentally click any content's links at random instead.

# Attachments
```
Please drag and drop the necessary data files (e.g. screenshot, logs, etc)
below.
```

**Comment by hollowaykeanho** [comment] 2023-02-23 03:05
Problem not seen in actual production across various deployments.

**Comment by hollowaykeanho** [comment] 2023-02-23 03:06
@CoryGalyna , pleae confirm.

**Comment by CoryGalyna** [comment] 2023-02-23 03:07
Visited those pages. Looks like the issue is specific to Google Chrome Debugger. Let's close this issue as will not fix since Hestia is not responsible for the matter.

**Closed** 2023-02-23 03:08 UTC
Labels: Bug, Will Not Fix/Implement, HestiaHUGO
